@baseUrl = http://localhost:3100/api

@taskId = {{task.response.body.$.id}}
@userId = {{task.response.body.$.userId}}

#Create task
# @name task
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Дверь мне запили. Срочно",
  "description": "Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.",
  "categoryId": 1,
  "price": 1000,
  "address": "переулок Дверной запил, 21",
  "city": "Moscow",
  "tags": ["дверь", "запилить"],
  "userId": "A123"
}

###

# Get task by ID
GET {{baseUrl}}/tasks/{{taskId}} HTTP/1.1

###

# Update task status by ID
PATCH {{baseUrl}}/tasks/5/status HTTP/1.1
Content-Type: application/json

{
  "userId": "6458f530cbf848d544c9548c",
  "status": "Canceled"
}

###

# Add response to task by ID
PATCH {{baseUrl}}/tasks/{{taskId}}/response HTTP/1.1
Content-Type: application/json

{
  "userId": "B111"
}

###

# Add contractor to task by ID
PATCH {{baseUrl}}/tasks/{{taskId}}/contractor HTTP/1.1
Content-Type: application/json

{
  "contractorId": "A123",
  "userId": "B111"
}

###

# Get tasks
GET {{baseUrl}}/tasks?sortDirection=desc&limit=2&page=1 HTTP/1.1

###

# Get customer tasks count
GET {{baseUrl}}/tasks/customer/{{userId}} HTTP/1.1

###

# Get contractor tasks count
GET {{baseUrl}}/tasks/contractor/{{userId}}?status=Completed HTTP/1.1

###

# Get customer tasks
GET {{baseUrl}}/task/customer/2/my?sortDirection=desc&limit=2&page=1 HTTP/1.1

###

# Delete Task by ID
DELETE {{baseUrl}}/tasks/4 HTTP/1.1

###