@baseUrl = http://localhost:3100/api

#Create task
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Дверь мне запили. Срочно",
  "description": "Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.Запили дверь.",
  "price": 1000,
  "address": "переулок Дверной запил, 21",
  "tags": ["запилить"],
  "city": "Moscow"
}

###

# Get task by ID
GET {{baseUrl}}/tasks/77349651-e4a7-4bbe-bddc-576dd0e8b613 HTTP/1.1

###

# Get tasks
GET {{baseUrl}}/tasks?sortDirection=desc&tags=1&limit=2&page=1 HTTP/1.1

###

# Delete Task by ID
DELETE {{baseUrl}}/tasks/77349651-e4a7-4bbe-bddc-576dd0e8b613 HTTP/1.1

###