@baseUrl = http://localhost:3000/api

# Create a new user
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "fullName": "Spartan Spartanych",
  "email": "sparta@gmail.com",
  "city": "Москва",
  "password": "123456",
  "role": "Customer",
  "dateBirth": "2022-02-22"
}

###

# Get user by ID
GET {{baseUrl}}/auth/6429a367af70e280a3855b20 HTTP/1.1

###

# Login user by email and password
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "sparta@gmail.com",
  "password": "123456"
}

###