@baseUrl = http://localhost:3000/api

# Create a new user
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "fullName": "Spartan Spartanych",
  "email": "sparta@gmail.com",
  "city": "Moscow",
  "password": "123456",
  "role": "Customer",
  "dateBirth": "2022-02-22"
}

###

# Get user by ID
GET {{baseUrl}}/auth/643d76d219d0332770437681 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDNkNzZkMjE5ZDAzMzI3NzA0Mzc2ODEiLCJmdWxsbmFtZSI6IlNwYXJ0YW4gU3BhcnRhbnljaCIsImVtYWlsIjoic3BhcnRhQGdtYWlsLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImlhdCI6MTY4MTc0OTcyMiwiZXhwIjoxNjgxNzQ5NzIyfQ.QbhmSeW_nPqHxus-b-V1egpg9MNp3sihkKiwKKAGm_c

###

# Login user by email and password
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "sparta@gmail.com",
  "password": "123456"
}

###