@baseUrl = http://localhost:3300/api

@reviewId = {{review.response.body.$.id}}
@contractorId = {{review.response.body.$.contractorId}}

#Create review
# @name review
POST {{baseUrl}}/reviews/create HTTP/1.1
Content-Type: application/json

{
  "review": "Нраица, очень нраица. Рататаратараатататататататттаататататтававамываыаыавмыамывамвамывамывамывамывамывамывам",
  "taskId": 1,
  "contractorId": "6455dc009a24b824b6976f84",
  "userId": "6455dc009a24b824b6976f90",
  "rating": 5
}

###

# Get review by ID
GET {{baseUrl}}/reviews/{{reviewId}} HTTP/1.1

###

# Get review by task ID
GET {{baseUrl}}/reviews/task/1 HTTP/1.1

###

# Get reviews by contractor ID
GET {{baseUrl}}/reviews/{{contractorId}}/data HTTP/1.1

###

# Get rating sum by contractor ID
GET {{baseUrl}}/reviews/{{contractorId}}/sum HTTP/1.1

###

#Delete review by ID
DELETE {{baseUrl}}/reviews/{{reviewId}} HTTP/1.1

###