@baseUrl = http://localhost:3300/api

@reviewId = {{review.response.body.$.id}}
@contractorId = {{review.response.body.$.contractorId}}

#Create review
# @name review
POST {{baseUrl}}/reviews/create HTTP/1.1
Content-Type: application/json

{
  "review": "Нраица, очень нраица.",
  "taskId": "2",
  "contractorId": "asd-123",
  "rating": 5
}

###

# Get review by ID
GET {{baseUrl}}/reviews/{{reviewId}} HTTP/1.1

###

# Get review by ID
GET {{baseUrl}}/reviews/{{reviewId}} HTTP/1.1

###

# Get reviews by contractor ID
GET {{baseUrl}}/reviews/{{contractorId}} HTTP/1.1

###

# Get rating sum by contractor ID
GET {{baseUrl}}/reviews/{{contractorId}}/sum HTTP/1.1

###

#Delete review by ID
DELETE {{baseUrl}}/reviews/{{reviewId}} HTTP/1.1

###