@baseUrl = http://localhost:3200/api

@commentId = {{comment.response.body.$.id}}

#Create comment
# @name comment
POST {{baseUrl}}/comments/create HTTP/1.1
Content-Type: application/json

{
  "comment": "Изи пизи лемон сквизи",
  "taskId": "1"
}

###

# Get comment by ID
GET {{baseUrl}}/comments/{{commentId}} HTTP/1.1

###

# Get comments
GET {{baseUrl}}/comments?sortDirection=desc&limit=2&page=1 HTTP/1.1

###

#Delete comment by ID
DELETE {{baseUrl}}/comments/{{commentId}} HTTP/1.1

###